[config]
default_to_workspace = false

[env]
RUST_BACKTRACE = "1"
RUST_LOG = "binance_exporter=info"

[tasks.run]
args = ["run", "--release", "--", "${@}"]
command = "cargo"

[tasks.build_docker]
script = """
exec --fail-on-error docker buildx build -t ghcr.io/dovahcrow/binance-exporter .
"""
script_runner = "@duckscript"

